name: ccgr_env_cpu
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9
  - pandas
  - matplotlib
  - scikit-learn
  - keras
  - tensorflow=2.13.*
  - pip
  - pip:
    - Pillow