name: ccgr_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pandas
  - matplotlib
  - scikit-learn
  - keras=2.11
  - tensorflow=2.11
  - pillow
  - pip
  - pip:
    - Pillow


